# File synced from https://github.com/FasterSpeeding/Aurora-Fauxy
# Changes will not be persisted
[tools]
# Languages
go = "1.25"
python = "3"
rust = { version = "1.90.0", components = "rustc,cargo" }
# CLI tools
cargo-binstall = "1.15.6"
"go:github.com/schollz/croc/v10" = "v10.2.7"
flux2 = "2.7.3"
git-lfs = "3.7.0"
helm = "3.19.0"
uv = "0.9.8"
just = "1.43.0"
kubeseal = "0.32.2"
minikube = "1.37.0"
opentofu = "1.10.6"
yt-dlp = "2025.09.26"

[settings]
activate_aggressive = true
experimental = true
gpg_verify = true
lockfile = false
not_found_auto_install = false
paranoid = true
plugin_autoupdate_last_check_duration = "0"
go_skip_checksum = true

[settings.python]
compile = false
uv_venv_auto = true
